language: php

notifications:
  email: false
  slack:
    secure: JzGnFqEjxB4v1Pr94rMBRGlwz1ASKPtTUMHlyASnbcWyF/FORbpe7dm/RQFdVbOklzpFZ6ze3OpVRRSrSOfjZSBHLAN0AAczVjO4puIcvy5a9ZqOhpETtkkdJQM56/LYr3O4pFRQ6FO57Tcokq4IeuxdMbWTFnFnlsZjKnHE6m4=

php:
  - 5.5
  - 5.6

install: composer install -o

before_script:
  - mysql -e 'create database myapp_test;'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml